image: python:3.9-slim
# https://hub.docker.com/layers/library/python/3.9-slim
before_script:
  - python --version ; pip --version  # For debugging
  - pip install pipenv
  - cp site/Pipfile .
  - cp site/Pipfile.lock .
  - ls
  - pipenv install
  - pipenv graph
  - apt-get update

pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir public
    - pipenv run sphinx-build -n -b dirhtml site/ site/_build/dirhtml
    - cp -r site/_build/dirhtml/* public/
    - ls -alR public
  artifacts:
    paths:
       - public
  only:
    - master
